Repository bcakmakoglu/vue-flow, pull requests merged in 2022-10, with the labels that each got.

#293 fix(edges): use filter to remove orphaned edges
  packages/vue-flow/src/store/getters.ts
Labels: bug

#299 fix(viewpane,nodes): move resize observer to mounted hooks
  packages/vue-flow/src/container/NodeRenderer/NodeRenderer.vue
  packages/vue-flow/src/container/Viewport/Viewport.vue
Labels: bug

#298 feat(nodes): add from position to position change event
  packages/vue-flow/src/store/actions.ts
  packages/vue-flow/src/types/changes.ts
  packages/vue-flow/src/utils/drag.ts
Labels: enhancement

#308 chore: update workflow file
  .github/workflows/build-and-test.yml
Labels: chore

#303 feat(deps-dev): add changeset
  .changeset/README.md
  .changeset/config.json
  package.json
  pnpm-lock.yaml
Labels: enhancement, dependencies

#317 refactor: remove docs from build process and use separate script
  docs/package.json
  package.json
  turbo.json
Labels: internal

#322 examples: update quasar example
  examples/nuxt3/components/BasicFlow.vue
  examples/quasar/quasar.config.js
  examples/quasar/src/components/BasicFlow.vue
  examples/quasar/src/components/CustomizedFlow.vue
  examples/quasar/tsconfig.json
  pnpm-lock.yaml
Labels: chore

#327 chore(core): update styles
  packages/core/src/style.css
  packages/core/src/theme-default.css
Labels: chore

#344 Removed 0.x.x. warning from docs
  docs/src/guide/index.md
Labels: documentation

#355 chore: generate base changelog on push into master
  .github/workflows/changelog.yml
Labels: chore
