Repository bcakmakoglu/vue-flow, pull requests merged in 2023-10, with the labels that each got.

#1097 chore(docs): update node.md
  docs/src/guide/node.md
Labels: documentation

#1130 docs: fix kestra showcase link
  docs/components/home/Showcase.vue
Labels: documentation

#1133 chore(controls,minimap): update README title
  packages/controls/README.md
  packages/minimap/README.md
Labels: chore

#1132 docs: add meticulous
  docs/package.json
  docs/src/.vitepress/config.mts
  docs/src/.vitepress/theme/index.ts
  docs/src/.vitepress/theme/layouts/default.vue
  pnpm-lock.yaml
  turbo.json
Labels: documentation

#1140 refactor(core): add stub for addEventListener in useWindow
  packages/core/src/composables/useKeyPress.ts
  packages/core/src/composables/useWindow.ts
  packages/core/src/container/Viewport/Viewport.vue
  packages/core/src/utils/graph.ts
Labels: refactor

#1153 chore: release `1.24.1`
  .changeset/twenty-pears-act.md
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: release
