Repository bcakmakoglu/vue-flow, pull requests merged in 2023-02, with the labels that each got.

#635 chore(deps-dev): update deps-dev
  package.json
  pnpm-lock.yaml
Labels: chore

#648 chore: correct links in issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore

#662 chore(core): cleanup and replace `const` with `function`
  packages/core/src/components/Edges/EdgeText.vue
  packages/core/src/components/Edges/EdgeWrapper.ts
  packages/core/src/components/Panel/Panel.vue
  packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
  packages/core/src/container/NodeRenderer/NodeRenderer.vue
  packages/core/src/container/Viewport/Viewport.vue
  packages/core/src/utils/autopan.ts
  packages/core/src/utils/changes.ts
  packages/core/src/utils/drag.ts
  packages/core/src/utils/edge.ts
  packages/core/src/utils/general.ts
  packages/core/src/utils/graph.ts
  packages/core/src/utils/log.ts
  packages/core/src/utils/node.ts
  packages/core/src/utils/store.ts
  packages/core/src/utils/watch.ts
Labels: chore

#664 refactor(node-resizer): apply min width and height with aspect ratio
  packages/node-resizer/src/ResizeControl.vue
Labels: refactor

#669 chore(core): remove any typecast
  packages/core/src/store/actions.ts
Labels: chore

#670 refactor(core): use watcheffect to observe node dimensions
  packages/core/src/components/Nodes/NodeWrapper.vue
  packages/core/src/container/NodeRenderer/NodeRenderer.vue
Labels: refactor

#676 fix: Run correctly when used alongside `@vue/compat`
  packages/background/src/Background.vue
  packages/controls/src/ControlButton.vue
  packages/controls/src/Controls.vue
  packages/core/src/components/A11y/A11yDescriptions.vue
  packages/core/src/components/ConnectionLine/ConnectionLine.vue
  packages/core/src/components/Edges/BaseEdge.ts
  packages/core/src/components/Edges/BezierEdge.ts
  packages/core/src/components/Edges/EdgeAnchor.ts
  packages/core/src/components/Edges/EdgeLabelRenderer.vue
  packages/core/src/components/Edges/EdgeText.vue
  packages/core/src/components/Edges/EdgeWrapper.ts
  packages/core/src/components/Edges/SimpleBezierEdge.ts
  packages/core/src/components/Edges/SmoothStepEdge.ts
  packages/core/src/components/Edges/StepEdge.ts
  packages/core/src/components/Edges/StraightEdge.ts
  packages/core/src/components/Handle/Handle.vue
  packages/core/src/components/Nodes/DefaultNode.ts
  packages/core/src/components/Nodes/InputNode.ts
  packages/core/src/components/Nodes/NodeWrapper.vue
  packages/core/src/components/Nodes/OutputNode.ts
  packages/core/src/components/NodesSelection/NodesSelection.vue
  packages/core/src/components/Panel/Panel.vue
  packages/core/src/components/UserSelection/UserSelection.vue
  packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
  packages/core/src/container/EdgeRenderer/Marker.vue
  packages/core/src/container/EdgeRenderer/MarkerDefinitions.vue
  packages/core/src/container/NodeRenderer/NodeRenderer.vue
  packages/core/src/container/Pane/Pane.vue
  packages/core/src/container/Viewport/Transform.vue
  packages/core/src/container/Viewport/Viewport.vue
  packages/core/src/container/VueFlow/VueFlow.vue
  packages/minimap/src/MiniMap.vue
  packages/minimap/src/MiniMapNode.ts
  packages/node-resizer/src/NodeResizer.vue
  packages/node-resizer/src/ResizeControl.vue
  packages/node-resizer/src/ResizeControlLine.vue
  packages/node-toolbar/src/NodeToolbar.vue
  packages/pathfinding-edge/src/arrow/PerfectArrow.vue
  packages/pathfinding-edge/src/edge/PathFindingEdge.vue
Labels: bug

#688 chore(core): update prevent scrolling comment
  packages/core/src/types/flow.ts
Labels: documentation

#692 chore(core): update functional component types
  packages/core/src/components/Edges/BaseEdge.ts
  packages/core/src/components/Nodes/DefaultNode.ts
  packages/core/src/components/Nodes/InputNode.ts
  packages/core/src/components/Nodes/OutputNode.ts
Labels: chore

#715 tests: add custom edge test
  tests/cypress/component/2-vue-flow/customEdge.cy.ts
  tests/cypress/component/2-vue-flow/customNode.cy.ts
Labels: tests
