Repository bcakmakoglu/vue-flow, pull requests merged in 2023-03, with the labels that each got.

#730 chore: release `1.15.4`
  .changeset/young-glasses-swim.md
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: release

#738 chore(deps): cleanup deps
  docs/package.json
  package.json
  packages/background/package.json
  packages/controls/package.json
  packages/core/package.json
  packages/core/src/auto-imports.d.ts
  packages/minimap/package.json
  packages/node-resizer/package.json
  packages/node-toolbar/package.json
  packages/pathfinding-edge/package.json
  pnpm-lock.yaml
  tests/package.json
  tooling/eslint-config/package.json
  tooling/tsconfig/package.json
  tooling/vite-config/package.json
Labels: chore

#766 fix(core,nodes): unwrap refs and pass props
  .changeset/ninety-crews-remember.md
  .changeset/twelve-seahorses-play.md
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: release

#779 chore(core): cleanup
  packages/core/src/container/VueFlow/VueFlow.vue
  packages/core/src/utils/graph.ts
  packages/core/src/utils/store.ts
Labels: chore

#788 chore(core): accept invalid handle id config
  packages/core/src/utils/edge.ts
Labels: chore

#787 fix(core): remove erroneous window.stop in EdgeRenderer
  packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
Labels: bug

#793 chore: release `1.17.1`
  .changeset/green-adults-design.md
  .changeset/rare-walls-wash.md
  .changeset/rude-ties-study.md
  .changeset/smooth-dancers-collect.md
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: release

#813 chore(docs): update pinia example
  docs/components/examples/pinia/PiniaExample.vue
Labels: documentation

#816 chore: release `1.17.3`
  .changeset/young-lizards-mix.md
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: release
