Repository bcakmakoglu/vue-flow, pull requests merged in 2023-07, with the labels that each got.

#1010 fix(node-resizer): Use correct class name and style for handle controls
  packages/node-resizer/src/NodeResizer.vue
Labels: bug

#1003 chore(core): cleanup
  packages/core/src/components/UserSelection/UserSelection.vue
  packages/core/src/composables/useViewport.ts
  packages/core/src/container/Pane/Pane.vue
Labels: chore

#1014 fix(core): clamp node extent by node dimensions to avoid overflow
  .changeset/perfect-kings-complain.md
  packages/core/src/utils/drag.ts
Labels: bug

#1013 refactor(core): resolve slots before returning default component
  .changeset/hot-nails-cough.md
  .changeset/rude-pets-build.md
  packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
  packages/core/src/container/NodeRenderer/NodeRenderer.vue
  packages/core/src/types/node.ts
Labels: refactor

#1018 chore: release `1.21.1`
  .changeset/lazy-eels-think.md
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: release

#1050 chore: release `1.22.1`
  .changeset/bright-lions-play.md
  .changeset/happy-crews-wash.md
  .changeset/thick-students-reflect.md
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: release

#1057 chore: release `1.22.2`
  .changeset/light-pets-bake.md
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: release
