Repository bcakmakoglu/vue-flow, pull requests merged in 2025-08, with the labels that each got.

#1912 fix(controls): add `type="button"` to avoid form submissions (#1911)
  .changeset/clever-rabbits-guess.md
  docs/src/guide/node.md
  packages/controls/src/ControlButton.vue
Labels: bug

#1904 feat: add optional chaining to prevent types errors and add an example of helper lines
  docs/examples/helper-lines/App.vue
  docs/examples/helper-lines/HelperLines.vue
  docs/examples/helper-lines/index.ts
  docs/examples/helper-lines/initialElements.ts
  docs/examples/helper-lines/style.css
  docs/examples/helper-lines/utils.ts
  docs/examples/index.ts
  docs/src/.vitepress/config.mts
  docs/src/examples/helper-lines.md
  docs/src/guide/node.md
Labels: documentation

#1913 fix(core): emit node drag-start, drag and drag-end events on selection drag
  .changeset/nine-games-deny.md
  packages/core/src/components/NodesSelection/NodesSelection.vue
Labels: bug

#1914 fix(core): calculate overlapping area correctly
  .changeset/afraid-lies-deny.md
  packages/core/src/store/actions.ts
Labels: bug

#1923 fix(minimap): use 1 as zoomstep for minimap and apply factor based on macOs
  .changeset/dull-swans-march.md
  .changeset/tender-geckos-sniff.md
  packages/core/src/index.ts
  packages/minimap/src/MiniMap.vue
Labels: bug

#1922 fix(core): fetch correct source and target nodes for isValidConnection
  .changeset/stale-phones-cross.md
  packages/core/src/utils/handle.ts
Labels: bug

#1924 refactor(core): use event target for Handle pointer down events
  .changeset/rude-suns-refuse.md
  packages/core/src/composables/useHandle.ts
Labels: refactor

#1936 fix(core): skip resize handler if node not visible
  .changeset/stupid-bags-itch.md
  packages/core/src/composables/useResizeHandler.ts
Labels: bug

#1938 fix(core): prevent multi touch from aborting connections
  .changeset/selfish-geese-attack.md
  packages/core/src/composables/useHandle.ts
  packages/core/src/container/Viewport/Viewport.vue
Labels: bug
