Repository bcakmakoglu/vue-flow, pull requests merged in 2025-03, with the labels that each got.

#1781 fix(core): avoid removing handle bounds on handle unmount
  .changeset/plenty-rocks-impress.md
  packages/core/src/components/Handle/Handle.vue
Labels: bug

#1785 fix(node-toolbar): set default value for isVisible to undefined
  .changeset/olive-fishes-fetch.md
  packages/node-toolbar/src/NodeToolbar.vue
Labels: bug

#1779 chore: next release
  .changeset/olive-fishes-fetch.md
  .changeset/plenty-rocks-impress.md
  .changeset/shaggy-penguins-invite.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/node-toolbar/CHANGELOG.md
  packages/node-toolbar/package.json
Labels: release

#1789 fix(core): unwrap ref when checking if connection in progress
  .changeset/tame-cars-occur.md
  packages/core/src/container/Pane/Pane.vue
Labels: bug

#1790 chore: next release
  .changeset/tame-cars-occur.md
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: release

#1794 fix(core): use null as fallback id for edge source handle
  .changeset/cuddly-bugs-switch.md
  packages/core/src/components/Edges/EdgeWrapper.ts
Labels: bug

#1793 fix(core): defer connection lookup
  .changeset/smooth-pillows-laugh.md
  packages/core/src/store/actions.ts
Labels: bug

#1798 fix(core): reset drag items on drag end
  .changeset/old-moose-fly.md
  packages/core/src/composables/useDrag.ts
Labels: bug

#1807 fix(core): add button to elements to ignore in useKeyPress
  .changeset/lemon-terms-joke.md
  packages/core/src/composables/useKeyPress.ts
Labels: bug

#1809 chore: next release
  .changeset/lemon-terms-joke.md
  .changeset/thick-owls-double.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/minimap/CHANGELOG.md
  packages/minimap/package.json
Labels: release

#1797 docs: correct template syntax
  docs/src/guide/getting-started.md
Labels: documentation
